name: MappingGZ
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.7
  - bokeh
  - pip
  - geopandas
  - descartes
  - ipython
  - ipywidgets
  - jupyterlab
  - pysal
  - nbconvert
  - networkx
  - scikit-learn
  - scikit-gstat
  - seaborn
#  - statsmodels
#  - segregation
#  - watermark
  - rasterio
  - folium
  - cenpy
  - splot
  - contextily
  - rioxarray
  - geopy
